# -*- coding: utf-8 -*-
"""Proyek_Analisis_Data_Bike_sharing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLSFWGqc0QQwDus_unrli3JYKZLFZLqG

# Proyek Analisis Data: Bike Sharing Dataset

## Menentukan Pertanyaan Bisnis

- Diantara musim semi dan musim gugur, dimusim apa penyewaan paling banyak?
- pada waktu kapan yang paling banyak melakukan registered?
- Apakah peminjaman sepeda lebih tinggi pada hari kerja dibandingkan
akhir pekan?

## Import Semua Packages/Library yang Digunakan
"""

#memanggil semua library yang digunakan
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

#Menampilkan 5 baris pertama pada data day.csv
day_df = pd.read_csv("day.csv")
day_df.head()

#Memuat 5 baris pertama data hour.csv
hour_df = pd.read_csv("hour.csv")
hour_df.head()

"""### Assessing Data"""

day_df.info()
hour_df.info()

"""Berdasarkan informasi output diatas, terdapat keanehan pada kedua data. dibagian column **dteday** memiliki tipe data **object**, yang seharusnya bertipe **datetime**. saya akan mengganti nya pada proses cleaning data

"""

#Mengecek apakah ada Missing value pada dataset day_df
day_df.isnull().sum()

# Cek missing value dataset hour
hour_df.isnull().sum()

"""Ternyata setelah dicek, kedua data day_df dan hour_df tidak terdapat missing value. selanjutnya akan mengecek apakah ada data yang duplikat dari kedua data ini?"""

#cek duplikat data day_df
print("Jumlah duplikasi:", day_df.duplicated().sum())

#cek duplikasi data hour_df
print("Jumlah duplikasi:", hour_df.duplicated().sum())

"""ternyata setelah dicek, kedua data tersebut tidak memiliki nilai duplikat"""

#menampilkan ringkasan parameter statistik (mean, median, dll.) dari kolom numerik pada sebuah DataFrame.
day_df.describe()

hour_df.describe()

"""### Cleaning Data

Pada data day dan hour terdapat column workingday yang artinya jika hari libur atau holiday ditandai dengan 1 sedangkan jika tidak ditandai 0 pernyataan ini sebenarnya sudah diwakili oleh weekday dan holiday yang mana weekday : hari kerja dalam satu minggu dan holiday : hari libur atau tidak libur. jadi, dalam hal ini dilakukannya dropping/ penghapusan pada kolom workingday
"""

# Menghapus column workingday pada data day_df dan hour_df
day_df.drop("workingday", axis=1, inplace=True)
hour_df.drop("workingday", axis=1, inplace=True)

#menampilkan data yang sudah di drop
day_df.head()

hour_df.head()

"""seperti yang dilihat sudah tidak ada kolom workingday

selanjutnya akan melakukan penggantian nama kolom (rename), agar mudah untuk dibaca dan agar saya mudah untuk menganalisis nya. berikut keterangan kolom:
- dteday --> date_day
- season : (1:springer: semi, 2:summer: panas, 3:fall: gugur, 4:winter: dingin)
- yr --> year (0: 2011, 1:2012)
- mnth --> month ( 1 to 12)
- hr --> hour (0 to 23): jam 00.00-23.00
- holiday : weather day is holiday or not: hari libur atau tidak
- weekday --> day_of_week
- weathersit --> weather_sit :

1.   Clear, Few clouds, Partly cloudy, Partly cloudy (cuaca cerah ideal)
2.   Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist (berkabut, cuaca kurang ideal)
3. Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds (hujan,kondisi cuaca buruk)
4. Heavy Rain + Ice Pellets + Thunderstorm + Mist, Snow + Fog (kondisi cuaca sangat buruk
- temp : suhu sebenarnya yang dinormalisasi dengan membaginya dengan 41.
- atemp : suhu yang dirasakan (feels-like temperature) yang dinormalisasi dengan membaginya dengan 50.
-hum --> humidity: kelembapan yang dinormalisasi dengan membaginya oleh 100
- windspeed : kecepatan angin yang dinormalisasi dengan membaginya oleh 67  
- Casual: Pengguna yang tidak terdaftar, biasanya menyewa sepeda untuk jangka pendek atau sekali-kali.
- Registered: Pengguna yang terdaftar lebih sering melakukan penyewaan sepeda
- cnt --> total_rental : jumlah total sepeda yang disewa mencakup casual dan registered

**Rename column**
"""

#Rename kolom pada data day_df
day_df.rename(columns={
    "dteday": "date_day",
    "yr": "year",
    "mnth": "month",
    "weekday": "day_of_week",
    "weathersit": "weather_sit",
    "hum": "humidity",
    "cnt": "total_rental"
}, inplace=True)

#menampilkan data yang sudah di rename
day_df.head()

#Rename kolom pada data hour_df
hour_df.rename(columns={
    "dteday": "date_day",
    "yr": "year",
    "mnth": "month",
    "hr": "hour",
    "weekday": "day_of_week",
    "weathersit": "weather_sit",
    "hum": "humidity",
    "cnt": "total_rental"
}, inplace=True)

#menampilkan data yang sudah di rename kolom
hour_df.head()

day_df.info()
hour_df.info()

"""**Insight:**
- dari informasi data diatas, date_day masih bertipe object dan harus diubah menjadi datetime
-  pada kolom season, year, month, hour, day_of_week, wether_sit seharusnya dtype categorical bukan int jadi harus diubah
"""

#Mengubah kolom date_day menjadi tipe datetime untuk kedua data
datetime_columns = ["date_day"]

for column in datetime_columns:
  day_df[column] = pd.to_datetime(day_df[column])
  hour_df[column] = pd.to_datetime(hour_df[column])
day_df.info()
hour_df.info()

"""bisa dilihat, kolom date_day sudah berubah menjadi tipe data **datetime** yang sebelumnya **object**"""

#Mengubah kolom season,year,month,hour,day_of_week dan weather_sit menjadi bertipe category yang semula int
categorical_columns_day = ["season", "year", "month", "day_of_week", "weather_sit"]
categorical_columns_hour = ["season", "year", "month", "hour", "day_of_week", "weather_sit"] # tambahkan kolom hour

for column in categorical_columns_day:
   day_df[column] =  day_df[column].astype("category")
for column in categorical_columns_hour:
   hour_df[column] =  hour_df[column].astype("category")

day_df.info()
hour_df.info()

"""bisa dilihat, pada kolom season,year,month,hour,day_of_week dan weather_sit sudah berubah menjadi dtype **category**

**Melakukan Penjabaran nilai data** sesuai dengan keterangan kolom pada kedua data

**Menjabarkan atau mengubah nilai kolom season, year, month, day_of_week, weather_sit agar mudah dipahami**
"""

# mengubah nilai season menjadi deskripsi musim agar mudah dipahami 1:Spring, 2:Summer, 3:Fall, 4:Winter
column_season = {
    1: "Spring", 2: "Summer", 3: "Fall", 4: "Winter"
}
day_df["season"]= day_df["season"].replace(column_season)
hour_df["season"]= hour_df["season"].replace(column_season)

#menjabarkan nilai kolom year 0: 2011, 1:2012
column_year = {
    0: 2011,
    1: 2012
}
day_df["year"]= day_df["year"].replace(column_year)
hour_df["year"]= hour_df["year"].replace(column_year)

#menjabarkan  nilai kolom month menjadi 1:Jan, 2:Feb, 3:Mar, 4:Apr, 5:May, 6:Jun, 7:Jul, 8:Aug, 9:Sep, 10:Oct, 11:Nov, 12:Dec
column_month = {
    1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr", 5: "May", 6: "Jun", 7: "Jul", 8: "Aug", 9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec"
}
day_df["month"]= day_df["month"].replace(column_month)
hour_df["month"]= hour_df["month"].replace(column_month)

#menjabarkan nilai kolom day_of_week menjadi  0:Sun, 1:Mon, 2:Tue, 3:Wed, 4:Thu, 5:Fri, 6:Sat
column_day_of_week = {
    0: "Sun", 1: "Mon", 2: "Tue", 3: "Wed", 4: "Thu", 5: "Fri", 6: "Sat"
}
day_df["day_of_week"]= day_df["day_of_week"].replace(column_day_of_week)
hour_df["day_of_week"]= hour_df["day_of_week"].replace(column_day_of_week)

#Menjabarkan nilai kolom weather_sit menjadi 1: Clear, 2:Mist, 3:Light rain, 4: Heavy Rain
column_weather_sit = {
    1: "Clear", 2: "Mist", 3: "Light rain", 4: "Heavy Rain"
}
day_df["weather_sit"]= day_df["weather_sit"].replace(column_weather_sit)
hour_df["weather_sit"]= hour_df["weather_sit"].replace(column_weather_sit)

#mengecek perubahan
day_df.head()

#cek perubahan
hour_df.head()

"""**Membuat kolom baru dengan nama category_day**"""

#membuat kolom baru bernama category_day untuk mengkategorikan weeday dan weekend
def category_day(day_of_week):
  if day_of_week <= "Thu":
    return "weekday"
  else:
    return "weekend"
day_df["category_day"] = day_df["day_of_week"].apply(category_day)
hour_df["category_day"] = hour_df["day_of_week"].apply(category_day)
print(day_df.head())
print(hour_df.head())

#Mengecek apakah kolom category_day sudah benar dibuat
day_df.head()

"""bisa dilihat hasilnya sudah dibuatkan kolom baru bernama category_day

## Exploratory Data Analysis (EDA)

### Explore data day_df
"""

#melihat rangkuman parameter statistik dari data day_df
day_df.describe(include="all")

"""**Insight:**
- dilihat dari rangkuman parameter statistik, kita memiliki pelanggan yang menyewa sebanyak 731.000000 dengan top month bulan jan(january)
- pada kolom holiday max 1 dengan standar deviasi 0,167155
"""

#melihat jumlah total_rental berdasarkan season
day_df.groupby(by="season").total_rental.sum().sort_values(ascending=False)

"""berdasarkan tabel, total rental yang paling tinggi adalah pada musim fall(gugur) sebanyak 1061129 dan yang paling rendah ada di season spring (semi) dengan pelanggan sebanyak 471348"""

#Melihat demografi pelanggan berdasarkan season dengan nilai max min setiap casual dan registered
day_df.groupby(by="season").agg({
    "total_rental": "sum",
    "casual": ["min", "max"],
    "registered": ["min", "max"]
})

"""berdasarkan tabel diatas, season fall menduduki tingkat tertinggi dari total_rental diantara yang lain sebanyak 1061129 dengan nilai casual penyewaan dalam jangka pendek paling rendah biasa nya min 118 dan max dan nilai max 3160 dan jumlah yag registered atau sering mendaftar untuk sewal dengan nilai min 889 dan max 6917.   """

# melihat penyebaran pelanggan berdasarkan season jumlah seluruh nya dengan nilai seluruh casual dan registered
day_df.groupby(by="season").agg({
    "casual": ["sum"],
    "registered": ["sum"]
})

"""berdasarkan tabel diatas, pelanggan yang menyewa secara casual atau penyewaan jangka pendek tidak telalu sering menyewa yang paling tinggi adalah di season fall dengan angka 226091 dan registered 835038"""

#melihat seberapa banyak jumlah penyewa berdasarkan musim semi dan musim gugur
#filter data hanya untuk musim semi dan musim gugur berdasarkan total jumlah penyewa/ rental (Total_rental)
df_filtered = day_df.loc[day_df["season"].isin(["Spring", "Fall"]), 'total_rental'].groupby(day_df['season']).sum()
# menampilkan hasil
print(df_filtered)

"""ternyata yang paling banyak melakukan sewa sepeda diantara musim semi dan gugur, yang paling tinggi adalah pada musim gugur(fall) sebanyak 1061129 sedangkan musim semi(spring) menyentuh angka 471348

### Explore data hour_df
"""

#melihat rangkuman parameter statistik dari data hour_df
hour_df.describe(include="all")

"""berdasarkan data tersebut, kita memiliki pelanggan yang menyewa sebanyak 17379 orang dengan top year nya ada di tahun 2012 dengan freq 8734, top month may dan top hour 17.00 dan sebagainya"""

# melihat penyebaran pelanggan yang melakukan registered berdasarkan hour
hour_df.groupby(by="hour").registered.sum().sort_values(ascending=False)

"""berdasarkan tabel, pelanggan yang paling banyak melakukan sewa sepeda atau registered adalah pada **jam 17.00** sebanyak **282640** orang dan dijam **04.00** sedikit yang melakukan penyewaan sepeda yaitu dengan angka **3554** orang."""

#melihat perbandingan jumlah rental sepeda berdasarkan kategori hari weekday dan weekend
hour_df.groupby(by="category_day").total_rental.sum().sort_values(ascending=False)

"""seperti yang terlihat, pelanggan yang melakukan sewa sepeda lebih banyak pada kategori weekday dengan angka 2350522 dibanding dengan weekend yang menyentuh angka 942157"""

#melihat persebaran pelanggan yang menyewa sepeda dengan kategori weekday dan weekend berdasarkan total rental keseluruhan, registered dan casual
day_df.groupby(by="category_day").agg({
    "total_rental": "sum",
    "registered": "sum",
    "casual": "sum"
})

"""## Visualization & Explanatory Analysis

### Pertanyaan 1: Diantara musim semi dan musim gugur, dimusim apa penyewaan paling banyak?
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Memfilter data untuk musim Spring dan Fall saja
filtered_df = day_df[day_df['season'].isin(["Spring", "Fall"])]

# Mengatur urutan manual agar Spring muncul pertama
filtered_df["season"] = pd.Categorical(filtered_df["season"], categories=["Fall", "Spring"], ordered=True)

# Membuat warna hanya untuk Spring dan Fall
colors = ['lightskyblue']

# Membuat grafik bar
plt.figure(figsize=(10, 5))

# Plot bar chart dengan urutan yang sudah diatur
sns.barplot(x="season", y="total_rental", data=filtered_df.sort_values(by="season"), palette=colors)

# Menambahkan judul dan label
plt.title("Jumlah Total Rental Berdasarkan Season Spring dan Fall", fontsize=15)
plt.xlabel("Season", fontsize=12)
plt.ylabel("Total Rental", fontsize=12)

# Menampilkan plot
plt.show()

"""berdasarkan visualisasi diatas, musim fall adalah yang terbanyak dibanding musim spring"""

# Menghitung total_rental berdasarkan season
season_rentals = day_df.groupby(by="season").total_rental.sum().reset_index()

# Mengatur urutan season dengan Fall pertama, Summer kedua, Winter ketiga, dan Spring terakhir
season_rentals["season"] = pd.Categorical(season_rentals["season"],
                                          categories=["Fall", "Summer", "Winter", "Spring"],
                                          ordered=True)

# Membuat warna untuk setiap season, dengan warna khusus untuk Fall
colors = ['lightskyblue', 'lightgray', 'lightgray', 'lightgray']

# Membuat grafik bar
plt.figure(figsize=(10, 5))
sns.barplot(x="season", y="total_rental", data=season_rentals, palette=colors)

# Menambahkan judul dan label
plt.title("Jumlah Total Rental Berdasarkan Season", fontsize=14)
plt.xlabel("Season", fontsize=12)
plt.ylabel("Total Rental", fontsize=12)

# Menampilkan plot
plt.show()

"""### Pertanyaan 2: Pada waktu kapan yang paling banyak melakukan registered?"""

import matplotlib.pyplot as plt
import seaborn as sns

# Mengelompokkan data berdasarkan 'hour' dan menghitung total 'registered'
hour_registered = hour_df.groupby('hour')['registered'].sum().reset_index()

#membuat colors khusus untuk jam 17 diwarna lightskyblue yang artinya jam paling banyak registered
#sedangkan yang lainnya berwarna abu-abu
colors = ['lightskyblue'if hour == 17  else 'lightgray' for hour in hour_registered['hour']]

# Membuat grafik bar
plt.figure(figsize=(10, 6))
sns.barplot(x="hour", y="registered", data=hour_registered, palette=colors)

# Menambahkan judul dan label
plt.title("Total Registered Berdasarkan Jam", fontsize=16)
plt.xlabel("Jam (Hour)", fontsize=12)
plt.ylabel("Jumlah Registered", fontsize=12)

# Menampilkan plot
plt.show()

"""**Insight:**
- pelanggan banyak melakukan registered rental sepeda pada jam 17.00

### Pertanyaan 3: Apakah peminjaman sepeda lebih tinggi pada hari kerja dibanding dengan akhir pekan?
"""

#melihat banyaknya penyewa berdasarkan kategori hari
hour_df.groupby(by="category_day").total_rental.sum().sort_values(ascending=False)

import matplotlib.pyplot as plt
# Menghitung total rental berdasarkan kategori hari
category_rental = day_df.groupby('category_day')['total_rental'].sum().reset_index()

# Membuat pie chart
plt.pie(category_rental['total_rental'], labels=category_rental['category_day'], autopct='%1.1f%%', startangle=90, colors=['#66b3ff', '#ff9999'])
plt.title('banyaknya Total Penyewaan Berdasarkan Kategori Hari (Weekday/Weekend)')
plt.show()

"""## Analisis Lanjutan (Opsional)"""

#menghitung rfm
date = max(hour_df["date_day"])
rfm_df = hour_df.groupby(by="total_rental").agg({
    "date_day": lambda x: (date - x.max()).days, #recency
    "hour": "count", #frequency
    "total_rental": "sum" #monetary
})
rfm_df.columns = ["recency", "frequency", "monetary"]
rfm_df

# menyimpan dataframe yang sudah bersih ke dalam file CSV
day_df.to_csv('day_bersih.csv', index=False)
hour_df.to_csv('hour_bersih.csv', index=False)

"""## Conclusion

- Diantara musim semi(spring) dan musim gugur yang paling banyak melakukan penyewaan adalah pada musim gugur(fall)
- waktu yang paling banyak melakukan registered adalah pada jam 17.00
- ya benar, peminjaman sepeda paling tinggi adalah pada kategori weekdays atau hari kerja
"""